// ! IF
const nombre="Tamara";
if (nombre=="Tamara"){
console.log("Hola Tamara");
}

// ! Un = es para asignar o reasignacion
// ! == es para comparaciones no extrictas
// !=== es para comparaciones estrictas

// VALORES TRUSIES Y FLASIES 
// STRING CON LONGITUD ES true
// string sin longitud es falsenumero 0 es false
// numero dsitinto de 0 es true
// object es true 
// array true 
// undefined false

